name: Build and Deploy Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        root_file: resume.tex
        latexmk_use_xelatex: false
        
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume-pdf
        path: resume.pdf
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        keep_files: false
        destination_dir: .